### ISSUE TITLE
The application only uses a processor core to search for invalid strings

### ISSUE THREAD

**Issue by vvbv** [izuzak/noam#14]
Greetings.

**Comment by izuzak** [comment]
Greetings to you too, @vvbv. Can you explain more clearly what you're trying to point out as a problem or as a potential improvement? I don't understand what the title you used for the issue means.

**Comment by vvbv** [comment]
I apologize, it is not possible multiprocessing in javascript, I will try to move everything to java. I expected an improvement using multiprocessing, to find non-valid strings with the language described by the automata, but the browser only allows one thread per website.
