### ISSUE TITLE
FSM2Regex: user input disappears after an attempt to copy RE

### ISSUE THREAD

**Issue by ivanov-v-v** [izuzak/noam#16]
For some reason, every time I write down my automaton description it gets replaced with some random automaton if I try to Ctrl+C the corresponding regular expression. It's frustrating. 
I am using Google Chrome on Ubuntu 16, if that helps.

**Comment by izuzak** [comment]
Thanks for the report, @ivanov-v-v :bow: Seems like a bug in how it detects whether the regex was modified or not (and the FSM automatically refreshes if the regex changed). 

Let me take a look 😄

**Comment by ivanov-v-v** [comment]
Thanks a lot, seems like the problem is gone now. :+1:
