### ISSUE TITLE
Regex simplification error

### ISSUE THREAD

**Issue by cgj** [izuzak/noam#18]
The following transformation is incorrect
R5
1.02.(6[8-9]|[7-9][0-9])|(1.(0[3-9]).([0-9][0-9][0-9]?))
Rule
ab(cd) => abcd
R6
1.02.6[8-9]|[7-9][0-9]|(1.(0[3-9]).([0-9][0-9][0-9]?))

For example, by removing the parentheses around the alternation, the expression now permits a match with the bare value "76" instead of needing at least "1.02.76" to match.

**Comment by izuzak** [comment]
Hi, @cgj 

> The following transformation is incorrect

The transformation is indeed correct. The character that the tool uses for alternation is `+` not `|`, so your `|` is interpreted as a regular character.

Here's a screenshot from the page explaining this:

http://ivanzuzak.info/noam/webapps/regex_simplifier/

<img width="590" alt="screen shot 2017-11-30 at 09 32 19" src="https://user-images.githubusercontent.com/38924/33421139-6b528f10-d5b1-11e7-8f44-5e64b66276ac.png">
