### ISSUE TITLE
Greater than sign can not be used as an alphabet symbol

### ISSUE THREAD

**Issue by matheus-mr** [izuzak/noam#25]
When I try to use the greater than sign (>) I get the Error: The specified object is not an alphabet symbol of the FSM.

Example:
#states
s15
s16
#initial
s15
#accepting
s16
#alphabet
>
#transitions
s15:>>s16

**Comment by matheus-mr** [comment]
Github is not showing the > under #alphabet on my example, but on the website I'm including it.

**Comment by izuzak** [comment]
Hi, @matheus-mr 👋 -- thanks for opening an issue!

I agree that the error message is a bit unclear, but what you observed is expected and documented behavior. Notice this line in the instructions:

http://ivanzuzak.info/noam/webapps/fsm_simulator/

"States and symbols are alphanumeric character strings and can not overlap."

So, the alphabet can contain only alphanumeric characters, not other characters. A `<` character is not alphanumeric.

I'm sorry if this is causing trouble for you, but for simplicity -- I don't have any plans for changing this. You might consider translating `>` characters to something else, then using the simulator, and then translating back when you're done.
