### ISSUE TITLE
Non deterministic for (aa)*

### ISSUE THREAD

**Issue by Linusssss573** [izuzak/noam#35]
Can someone show me a non-deterministic machine for (aa)* ?

**Comment by izuzak** [comment]
Hey @Linusssss573 👋 

Yeah, you can get a non-deterministic machine for that regex via this tool:

http://ivanzuzak.info/noam/webapps/fsm_simulator/

You can input a regex and it will output a DFA, NFA or eNFA for you. Here's what you'll get if you select an eNFA as output:

<img width="1115" alt="Screenshot 2020-05-20 at 10 51 49" src="https://user-images.githubusercontent.com/38924/82426320-fc288d80-9a87-11ea-8102-14fd5a7ec832.png">

Hope this helps!

**Comment by Linusssss573** [comment]
What does the $ mean?

**Comment by izuzak** [comment]
> What does the $ mean?

It's the character for an [empty string](https://en.wikipedia.org/wiki/Nondeterministic_finite_automaton#NFA_with_%CE%B5-moves). If there's a transition for that character, then that's an [epsilon-transition](https://en.wikipedia.org/wiki/Epsilon_transition)
