### ISSUE TITLE
Use the Kleene algoritm

### ISSUE THREAD

**Issue by Linusssss573** [izuzak/noam#36]
Use the Kleene algoritm on the machine down below:
![78](https://user-images.githubusercontent.com/65593167/83324864-49ff7b80-a268-11ea-9d9f-c8ec915942ff.png)

**Comment by izuzak** [comment]
This project offers a tool for transforming a DFA/NFA/eNFA into a regex: http://ivanzuzak.info/noam/webapps/fsm2regex/. If you'd like, you can use that. If you find a problem with that tool -- let me know.
