### ISSUE TITLE
why this regex is not defined?

### ISSUE THREAD

**Issue by RaminMiri** [izuzak/noam#4]
<([_:A-Za-z][-._:A-Za-z0-9]*(\s+[_:A-Za-z][-._:A-Za-z0-9]*\s*=\s*("[^"]*"|'[^']*'))*|\/[_:A-Za-z][-._:A-Za-z0-9]*)\s*|\/?>

**Comment by ibudiselic** [comment]
Hello Ramin!

Noam supports only a minimal syntax for regular expressions. In particular,
it doesn't support character classes and has no predefined character
classes (like \s). If I may ask, what is your use case i.e. what are you
trying to do? If you need a regular expression to parse some text, you
should just use the built in regexes in JavaScript. Noam is not meant to
replace that in any way. Instead, its purpose is to provide an easy way to
explore the relationship between regular expressions and finite automata.
The automaton that would result from your expression would be pretty big
and probably not very useful in that regard.

Best regards,
Ivan

**Comment by RaminMiri** [comment]
Hi Ivan,
it's XML  Regular Expressions for opening tag with 
attributes or a closing tag. Now I need to create DFA and I found out it's going to be complicated. ...but anyway thanks for your helpful simulator...and I appreciate if you know any other simulator that can help me with.
thank you.

**Comment by ibudiselic** [comment]
Ah, I see. I can't recommend any other tool unfortunately.

Ivan

**Comment by RaminMiri** [comment]
thanks
