### ISSUE TITLE
Transition graph not producing a graph

### ISSUE THREAD

**Issue by ghost** [izuzak/noam#42]
![image](https://user-images.githubusercontent.com/72623242/138597421-0c565d64-3493-46c4-b863-3f3a8386392c.png)

**Comment by HarrisonKhannah** [comment]
Hi I am getting this too and I am running a fresh install of Chrome with no extensions . Seems the JS lib is erroring? @izuzak

**Comment by izuzak** [comment]
> Hi I am getting this too and I am running a fresh install of Chrome with no extensions . Seems the JS lib is erroring? 

@HarrisonKhannah Hi 👋 Can you share the exact steps for reproducing the error? I'm on Chrome Version 95.0.4638.69 (Official Build) (x86_64) and still unable to trigger the problem. Also works fine in Safari.
