### ISSUE TITLE
I noticed there's an error thrown when converting regex to dfa

### ISSUE THREAD

**Issue by DebMaster** [izuzak/noam#47]
Uncaught TypeError: Cannot call a class as a function
    classCallCheck https://cdnjs.cloudflare.com/ajax/libs/viz.js/2.1.2/viz.js:36
    Viz https://cdnjs.cloudflare.com/ajax/libs/viz.js/2.1.2/viz.js:244
    drawGraph https://ivanzuzak.info/noam/webapps/fsm_simulator/scripts/fsm_simulator.js:58
    <anonymous> https://ivanzuzak.info/noam/webapps/fsm_simulator/scripts/fsm_simulator.js:281
    jQuery 
<img width="1161" alt="Screenshot 2021-11-23 at 09 25 32" src="https://user-images.githubusercontent.com/4119789/142984771-7cba8740-9309-432e-9ac3-9384817a0d9e.png">
2

**Comment by izuzak** [comment]
Thanks so much for letting me know, @DebMaster -- this should be fixed now 🍰
