### ISSUE TITLE
Which algorithm do you use for conversion?

### ISSUE THREAD

**Issue by coenig** [izuzak/noam#5]
What algorithms does noam use to convert an FSM to a regex and vice versa? 

I tried to do the same thing in Java (apparently there is no such thing available), but the only thing I found was a research paper which proved that for any FSM there is a regex, and gave an algorithm on the side. The generated regex's were enormous and not really of any use.

Can you tell me which algorithms you use (or do you even know of a ready-to-use Java solution)?

Btw. I like your little, handy web app very much!

Cheers!

**Comment by ibudiselic** [comment]
Hello coenig!

For FSM->regex we use Kleene's algorithm (
http://en.wikipedia.org/wiki/Kleene%27s_algorithm). It's a dynamic
programming algorithm that incrementally builds up regexes representing all
restricted paths between any two states of the FSM, gradually reducing the
restriction so to say. It's very similar to the Floyd-Warshall all pairs
shortest paths algorithm if you're familiar with that.

As for the other direction, I'm not sure exactly how the algorithm is
called, but it is very simple. It's basically this picture
http://userpages.umbc.edu/~squire/images/re2.gif or something very similar
to this. The idea is to parse the regex and recursively build the DFA
according to this picture. This is done by the toAutomaton function in
noam.re.js.

I hope this helps. If you have any further questions, please contact us
again!

Ivan

**Comment by coenig** [comment]
Thanks for the extremely quick answer! I will look at those algorithms...

Cheers

Lukas

**Comment by coenig** [comment]
Sorry to bother you again... Now I implemented the Kleene algorithm, and it appears to work - but my regex's don't turn out so nice and short as yours. (I already used some "common-sense" simplifications.) For example, your algo gets this quite short expression

(a(a+b))*(b((a+b)b*a)*(a+b)b*(b+$)+a+$+a(a+b))

for the below automaton while mine is MUCH larger. So, are you doing something particularly clever to simplify your Regex or does this indicate an error in my implementation?

Thanks again and in advance for your help!

#states
s0
s1
s2
s3
#initial
s0
#accepting
s0
s2
s3
#alphabet
a
b
#transitions
s0: a > s2
s0: b > s1
s3: a > s1
s1: a > s3
s1: b > s3
s3: b > s3
s2: a > s0
s2: b > s0

**Comment by ibudiselic** [comment]
There are a bunch of simplifications that are tried by the library. You can
see the code that does that near the top of the noam.re.js file. There's a
comment there that lists all the simplifications that are tried. I'm not
too familiar with that code as the other Ivan on the project wrote that,
but I'm sure he'll be able to give you some pointers if you'll have more
questions about it.

**Comment by coenig** [comment]
So there's more than one Ivan? :-)
I'll look at the code, thank you very much for the reply!

**Comment by ibudiselic** [comment]
Yes, there are two of us :)

**Comment by izuzak** [comment]
Hey, @coenig :wave:-- I'm the other Ivan. :)

I'm going to close this issue, but please leave a comment if you have any other questions about noam.
