### ISSUE TITLE
FSM2Regex missing "Create Automaton" button

### ISSUE THREAD

**Issue by Mikami382** [izuzak/noam#50]
Hi,

I notice that the Create Automaton button is missing from the page thus I cannot convert my FSM to regex. Could you please take a look at it? I also wrote you an email about the same problem in case you missed this one.

**Comment by izuzak** [comment]
Thanks for letting me know! The instructions were out of date -- I updated them just now. The button is not shown since it's not needed -- the page detects any changes and automatically displays results. :v:
