### ISSUE TITLE
Overlapping character issue in DFA

### ISSUE THREAD

**Issue by nurulalamador** [izuzak/noam#55]
If my language is,
```
L = { w | w start with "abb" and ends with "bac" }
```
then my regular expression should be this if I am not wrong:
```
(abb)(a+b+c)*(abb+$)(bac)
```

But this regular expression doesn't accept string `abbac` because here 'b' is overlapped.

**Comment by izuzak** [comment]
Thanks for opening an issue. Yeah, you are wrong -- the regular expression you wrote is not correct.

If the regular expression is `(abb)(a+b+c)*(abb+$)(bac)`, then that requires the string to start with `abb` and end with `bac`, so the minimal string is `abbbac`. So there's no way for that regex to generate the string `abbac`, which should be allowed by the language.

What you want is the regex `(abb)((ac)|((a+b+c)*(bac)))`.
