### ISSUE TITLE
JSDiff not working

### ISSUE THREAD

**Issue by ahsan2882** [izuzak/noam#56]
I have noticed that this project uses JSDiff for highlighting text differences, but when I simplify a regex in the regex gym, it doesn't highlight what has been changed in the simplification.
It would be nice to fix this feature.

**Comment by izuzak** [comment]
Thanks for reporting this and sorry for the trouble. This should be fixed now, as of https://github.com/izuzak/noam/commit/0f64ef34eff0112269f3140f0e221d92eb036a86

**Comment by ahsan2882** [comment]
Thanks a lot!
