### ISSUE TITLE
program not recognizing OR operator

### ISSUE THREAD

**Issue by jaysabe** [izuzak/noam#59]
![image](https://github.com/izuzak/noam/assets/121771938/c5e3c17f-9126-4a91-83f7-3b0efb2dbae2)

Program currently reads the OR operator (|) as its own state rather than its intended purpose.

**Comment by Michaelgathara** [comment]
```
aab+a*b*
```
Is probably what you are looking for

**Comment by izuzak** [comment]
Whoops, forgot to answer this 🙈 -- sorry about that, @jaysabe. Yeah, @Michaelgathara is right -- the `+` character is used as the `OR` operator, as per the instructions on the same page you screenshotted:

![Screenshot 2024-10-18 at 09 11 10@2x](https://github.com/user-attachments/assets/baf7ff4e-d5e1-45ba-9683-2104ea747a1e)
