### ISSUE TITLE
Supports lambda?

### ISSUE THREAD

**Issue by Jarvizx** [izuzak/noam#6]
Hello first of all thank you very much incredible tool. I wonder if spoporta expressions like
```
0+(λ+1)(λ+1)*0
```

**Comment by izuzak** [comment]
Not sure what the meaning of `λ` is there -- is that just another character or does it have special meaning?

Also, which tool are you referring to exactly? There are a few tools based on Noam:

https://github.com/izuzak/noam#web-apps

**Comment by Jarvizx** [comment]
oh! yes is Regular Expressions Gym
thz
